// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnaQjIrA5DKeEKSTq_nAYx-_NK3n-3A8',
    appId: '1:895819260842:web:ac56deaf07495aa43201d3',
    messagingSenderId: '895819260842',
    projectId: 'reccomendation-cafe-app',
    authDomain: 'reccomendation-cafe-app.firebaseapp.com',
    storageBucket: 'reccomendation-cafe-app.appspot.com',
    measurementId: 'G-GSTGX146TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PSzZZMCAjY7zRY77l4XIlPiK2z20o6o',
    appId: '1:895819260842:android:8a5f3f49dc6104503201d3',
    messagingSenderId: '895819260842',
    projectId: 'reccomendation-cafe-app',
    storageBucket: 'reccomendation-cafe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmneFwPoR4QMjniVrmWnJw-yLmmHuI8a4',
    appId: '1:895819260842:ios:52e5eac456da17963201d3',
    messagingSenderId: '895819260842',
    projectId: 'reccomendation-cafe-app',
    storageBucket: 'reccomendation-cafe-app.appspot.com',
    androidClientId: '895819260842-ha392t0lrpbuubqccohhm3914bsec65p.apps.googleusercontent.com',
    iosClientId: '895819260842-l9uuddvjghjmqbju4mm1f732nmm96rhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.reccomendationCafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmneFwPoR4QMjniVrmWnJw-yLmmHuI8a4',
    appId: '1:895819260842:ios:18b2aed5d645bd233201d3',
    messagingSenderId: '895819260842',
    projectId: 'reccomendation-cafe-app',
    storageBucket: 'reccomendation-cafe-app.appspot.com',
    androidClientId: '895819260842-ha392t0lrpbuubqccohhm3914bsec65p.apps.googleusercontent.com',
    iosClientId: '895819260842-b36m6rmr5lf2i3m4sf2f7dsg00m8kegg.apps.googleusercontent.com',
    iosBundleId: 'com.example.reccomendationCafeApp.RunnerTests',
  );
}
